// Integrated Labor Dashboard Data — auto-generated by update_il_dashboard.py
// Report week ending: 2026-07-05

const IL_DATA = {
  updated_date: "July 5, 2026",

  // Program totals (cumulative since launch May 1, 2026)
  total_quotes:  757,
  total_orders:  195,
  conv_rate:     25.8,

  // Cancel rate impact
  cancel_delta_7d:  -5.8,
  cancel_delta_30d: -2.8,
  cancel_savings:   23030,
  annualized_savings:        129422,
  projected_rollout_savings: "~$662,157",
  projected_rollout_agents:  220,

  labor_attach_rate: 1.7,   // manual — update when Snowflake container denominator available

  // Adoption
  active_agents: 43,
  total_agents:  79,

  // Prior week values (for trajectory narrative)
  prev_orders:  177,
  prev_quotes:  670,
  prev_savings: 38028,

  // Department breakdown
  depts: {
    Sales: { total: 15, active: 8, orders: 71, quotes: 251, pitch_rate: 20.4, conv_rate: 28.3 },
    SST:   { total: 18,   active: 15,   orders: 76,   quotes: 291,   pitch_rate: 28.1,   conv_rate: 26.1   },
    OB:    { total: 43,    active: 17,    orders: 21,    quotes: 146,    pitch_rate: 16.0,    conv_rate: 14.4    },
  },

  // Silent agent breakdown by location + dept
  silent_grid: [
  {
    "loc": "CLW",
    "dept": "Sales",
    "total": 14,
    "silent": 7
  },
  {
    "loc": "CLW",
    "dept": "SST",
    "total": 5,
    "silent": 0
  },
  {
    "loc": "CLW",
    "dept": "OB",
    "total": 13,
    "silent": 6
  },
  {
    "loc": "CNX",
    "dept": "Sales",
    "total": 1,
    "silent": 0
  },
  {
    "loc": "CNX",
    "dept": "SST",
    "total": 13,
    "silent": 3
  },
  {
    "loc": "CNX",
    "dept": "OB",
    "total": 30,
    "silent": 20
  }
],

  // Weekly new quotes & orders (last 8 weeks) — for stacked bar chart
  weekly_trends: [
  {
    "week": "5/11-5/17",
    "quotes": 94,
    "orders": 20
  },
  {
    "week": "5/18-5/24",
    "quotes": 78,
    "orders": 18
  },
  {
    "week": "5/25-5/31",
    "quotes": 73,
    "orders": 14
  },
  {
    "week": "6/1-6/7",
    "quotes": 95,
    "orders": 32
  },
  {
    "week": "6/8-6/14",
    "quotes": 104,
    "orders": 25
  },
  {
    "week": "6/15-6/21",
    "quotes": 95,
    "orders": 25
  },
  {
    "week": "6/22-6/28",
    "quotes": 85,
    "orders": 24
  },
  {
    "week": "6/29-7/5",
    "quotes": 77,
    "orders": 22
  }
],

  // Opportunity table
  opp_table: [
  {
    "dept": "OB",
    "desc": "All 43 fully trained",
    "silent": 26,
    "est_containers": "~3,320",
    "est_missed": "~442",
    "priority": "Critical"
  },
  {
    "dept": "Sales",
    "desc": "7 silent",
    "silent": 7,
    "est_containers": "~1,401",
    "est_missed": "~187",
    "priority": "High"
  },
  {
    "dept": "SST",
    "desc": "3 silent",
    "silent": 3,
    "est_containers": "~361",
    "est_missed": "~48",
    "priority": "Moderate"
  }
],

  // Agent roster (cumulative since launch)
  agents: [
  {
    "name": "HaH Agent",
    "dept": "HaH",
    "loc": "\u2014",
    "quoted": 55,
    "booked": 24
  },
  {
    "name": "Catherine Saitta",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 40,
    "booked": 22
  },
  {
    "name": "Amy Sisterman",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 67,
    "booked": 21
  },
  {
    "name": "Jeanielle Navarro",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 63,
    "booked": 20
  },
  {
    "name": "Carmie Nillama",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 45,
    "booked": 14
  },
  {
    "name": "Ted Johnson",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 29,
    "booked": 12
  },
  {
    "name": "Johnny Cardinale",
    "dept": "SST",
    "loc": "CLW",
    "quoted": 38,
    "booked": 11
  },
  {
    "name": "Sara Messenger",
    "dept": "SST",
    "loc": "CLW",
    "quoted": 29,
    "booked": 9
  },
  {
    "name": "Christina Morales",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 20,
    "booked": 7
  },
  {
    "name": "Gregory D. Bell",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 54,
    "booked": 6
  },
  {
    "name": "Kimberly Thebeau",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 31,
    "booked": 6
  },
  {
    "name": "Charmaine Bacay",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 52,
    "booked": 5
  },
  {
    "name": "Felicia Knight",
    "dept": "SST",
    "loc": "CLW",
    "quoted": 24,
    "booked": 5
  },
  {
    "name": "Christopher Monaldi",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 16,
    "booked": 4
  },
  {
    "name": "Mica Mae Maniego",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 18,
    "booked": 3
  },
  {
    "name": "Donald Alfaro",
    "dept": "SST",
    "loc": "CLW",
    "quoted": 16,
    "booked": 3
  },
  {
    "name": "James Onnagan",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 12,
    "booked": 3
  },
  {
    "name": "Princess Heidi Sesma",
    "dept": "Service",
    "loc": "CNX",
    "quoted": 12,
    "booked": 3
  },
  {
    "name": "Micah Joy Abrao",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 8,
    "booked": 3
  },
  {
    "name": "Katleen May Castro",
    "dept": "Sales",
    "loc": "CNX",
    "quoted": 14,
    "booked": 2
  },
  {
    "name": "Nicole Slater",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 13,
    "booked": 2
  },
  {
    "name": "Maria Concepcion Cauguiran",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 12,
    "booked": 2
  },
  {
    "name": "Almira Castro",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 11,
    "booked": 2
  },
  {
    "name": "Jake Russel Bernardino",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 8,
    "booked": 2
  },
  {
    "name": "Ednalyn Mirandilla",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 7,
    "booked": 2
  },
  {
    "name": "Carmie Ann Gorospe",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 7,
    "booked": 1
  },
  {
    "name": "Erik Goldring",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 2,
    "booked": 1
  },
  {
    "name": "Jessa Rey Belontindos",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 18,
    "booked": 0
  },
  {
    "name": "Marijoh Mae Lee",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 5,
    "booked": 0
  },
  {
    "name": "Syralee Mae Gamil",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 4,
    "booked": 0
  },
  {
    "name": "Aldwin Navarro",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 3,
    "booked": 0
  },
  {
    "name": "Annalee Bueno",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 3,
    "booked": 0
  },
  {
    "name": "Dale Besida",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 3,
    "booked": 0
  },
  {
    "name": "Kimberly Hewitt",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 3,
    "booked": 0
  },
  {
    "name": "Shannon Glendye",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 3,
    "booked": 0
  },
  {
    "name": "Dawn Carreiro",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 2,
    "booked": 0
  },
  {
    "name": "Fern Vallido",
    "dept": "Service",
    "loc": "\u2014",
    "quoted": 2,
    "booked": 0
  },
  {
    "name": "Matthew Floming",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 2,
    "booked": 0
  },
  {
    "name": "May Anthonette Clavel",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 2,
    "booked": 0
  },
  {
    "name": "Edison Viray",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 1,
    "booked": 0
  },
  {
    "name": "Sendy Firmalino",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 1,
    "booked": 0
  },
  {
    "name": "Shella Marie Francisco",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 1,
    "booked": 0
  },
  {
    "name": "Viviane Peux",
    "dept": "SST",
    "loc": "CLW",
    "quoted": 1,
    "booked": 0
  },
  {
    "name": "Aiko Noquillo",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Anna Kathrisse Serrano",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Brian Valdez",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Carol Brown",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Christian Jerick Sanchez",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Christopher Washington",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Cristal Apple Barredo",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Debra Springfield",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Dexter Weaver",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Erwin Cablao",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Eumarbel Dionglay",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Ferdinand Carlo Canete",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Frederick Hutchinson",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Gimarie Barastas",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Hannay Lozano",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Irish Verona",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Ivan Marc Lanestosa",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Ivy Fichtl",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "James Rebualos",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Jan Malvin Molina",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Jerico Galve",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Jerome Roger Rosites",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Jesse Vergara Jr",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Justin Brown",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Lienard Bryan Organo",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Marielle Coleen Placido",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Mary France Rodriguez",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Matthew Hepburn",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Michael Petersen",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Milkos Malcolm Orven Miguel",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Rene Dunn",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Richard Stoffregen",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Robert Dusenberry",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Ryan Dale Aldave",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Sandra Haun",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Thaddaeus Paulo Malig",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  }
],
};
