// Integrated Labor Dashboard Data — auto-generated by update_il_dashboard.py
// Report week ending: 2026-06-28

const IL_DATA = {
  updated_date: "June 28, 2026",

  // Program totals (cumulative since launch May 1, 2026)
  total_quotes:  670,
  total_orders:  177,
  conv_rate:     26.4,

  // Cancel rate impact
  cancel_delta_7d:  -6.3,
  cancel_delta_30d: -8.1,
  cancel_savings:   55007,
  annualized_savings:        660084,
  projected_rollout_savings: "~$3,723,551",
  projected_rollout_agents:  220,

  labor_attach_rate: 1.7,   // manual — update when Snowflake container denominator available

  // Adoption
  active_agents: 39,
  total_agents:  103,

  // Prior week values (for trajectory narrative)
  prev_orders:  142,
  prev_quotes:  552,
  prev_savings: 55007,

  // Department breakdown
  depts: {
    Sales: { total: 15, active: 7, orders: 65, quotes: 222, pitch_rate: 0, conv_rate: 29.3 },
    SST:   { total: 18,   active: 12,   orders: 72,   quotes: 263,   pitch_rate: 0,   conv_rate: 27.4   },
    OB:    { total: 43,    active: 5,    orders: 12,    quotes: 109,    pitch_rate: 0,    conv_rate: 11.0    },
  },

  // Silent agent breakdown by location + dept
  silent_grid: [
  {
    "loc": "CLW",
    "dept": "Sales",
    "total": 14,
    "silent": 7
  },
  {
    "loc": "CLW",
    "dept": "SST",
    "total": 5,
    "silent": 0
  },
  {
    "loc": "CLW",
    "dept": "OB",
    "total": 13,
    "silent": 7
  },
  {
    "loc": "CNX",
    "dept": "Sales",
    "total": 1,
    "silent": 0
  },
  {
    "loc": "CNX",
    "dept": "SST",
    "total": 13,
    "silent": 4
  },
  {
    "loc": "CNX",
    "dept": "OB",
    "total": 30,
    "silent": 20
  }
],

  // Weekly new quotes & orders (last 8 weeks) — for stacked bar chart
  weekly_trends: [
  {
    "week": "6/22-6/28",
    "quotes": 670,
    "orders": 177
  }
],

  // Opportunity table
  opp_table: [
  {
    "dept": "OB",
    "desc": "All 43 fully trained",
    "silent": 38,
    "est_containers": "~3,320",
    "est_missed": "~442",
    "priority": "Critical"
  },
  {
    "dept": "Sales",
    "desc": "8 silent",
    "silent": 8,
    "est_containers": "~1,401",
    "est_missed": "~187",
    "priority": "High"
  },
  {
    "dept": "SST",
    "desc": "6 silent",
    "silent": 6,
    "est_containers": "~361",
    "est_missed": "~48",
    "priority": "Moderate"
  }
],

  // Agent roster (cumulative since launch)
  agents: [
  {
    "name": "Catherine Saitta",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 38,
    "booked": 20
  },
  {
    "name": "Jeanielle Navarro",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 59,
    "booked": 19
  },
  {
    "name": "Amy Sisterman",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 58,
    "booked": 18
  },
  {
    "name": "Carmie Nillama",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 42,
    "booked": 13
  },
  {
    "name": "Ted Johnson",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 29,
    "booked": 12
  },
  {
    "name": "Johnny Cardinale",
    "dept": "SST",
    "loc": "CLW",
    "quoted": 33,
    "booked": 10
  },
  {
    "name": "Sara Messenger",
    "dept": "SST",
    "loc": "CLW",
    "quoted": 23,
    "booked": 8
  },
  {
    "name": "Gregory D. Bell",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 51,
    "booked": 6
  },
  {
    "name": "Kimberly Thebeau",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 28,
    "booked": 5
  },
  {
    "name": "Felicia Knight",
    "dept": "SST",
    "loc": "CLW",
    "quoted": 21,
    "booked": 5
  },
  {
    "name": "Christina Morales",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 15,
    "booked": 5
  },
  {
    "name": "Christopher Mondaldi",
    "dept": "Unknown",
    "loc": "\u2014",
    "quoted": 14,
    "booked": 4
  },
  {
    "name": "Isaac Zuniga",
    "dept": "Unknown",
    "loc": "\u2014",
    "quoted": 6,
    "booked": 4
  },
  {
    "name": "Mica Mae Maniego",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 18,
    "booked": 3
  },
  {
    "name": "Donald Alfaro",
    "dept": "SST",
    "loc": "CLW",
    "quoted": 15,
    "booked": 3
  },
  {
    "name": "James Onnagan",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 12,
    "booked": 3
  },
  {
    "name": "Princess Heidi Sesma",
    "dept": "Service",
    "loc": "CNX",
    "quoted": 9,
    "booked": 3
  },
  {
    "name": "Micah Joy Abrao",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 5,
    "booked": 3
  },
  {
    "name": "Moises Franco",
    "dept": "Unknown",
    "loc": "\u2014",
    "quoted": 5,
    "booked": 3
  },
  {
    "name": "Damian Zambrano",
    "dept": "Unknown",
    "loc": "\u2014",
    "quoted": 2,
    "booked": 3
  },
  {
    "name": "Charmaine Bacay",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 44,
    "booked": 2
  },
  {
    "name": "Nicole Slater",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 13,
    "booked": 2
  },
  {
    "name": "Maria Concepcion Cauguiran",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 12,
    "booked": 2
  },
  {
    "name": "Almira Castro",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 11,
    "booked": 2
  },
  {
    "name": "Ednalyn Mirandilla",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 7,
    "booked": 2
  },
  {
    "name": "Jake Russel Bernardino",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 4,
    "booked": 2
  },
  {
    "name": "Erick Villa",
    "dept": "Unknown",
    "loc": "\u2014",
    "quoted": 3,
    "booked": 2
  },
  {
    "name": "Katleen May Castro",
    "dept": "Sales",
    "loc": "CNX",
    "quoted": 3,
    "booked": 2
  },
  {
    "name": "Carmie Ann Gorospe",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 7,
    "booked": 1
  },
  {
    "name": "Oscar Vicente",
    "dept": "Unknown",
    "loc": "\u2014",
    "quoted": 4,
    "booked": 1
  },
  {
    "name": "Araceli Farfan",
    "dept": "Unknown",
    "loc": "\u2014",
    "quoted": 2,
    "booked": 1
  },
  {
    "name": "Attenas Martinez",
    "dept": "Unknown",
    "loc": "\u2014",
    "quoted": 2,
    "booked": 1
  },
  {
    "name": "Erik Goldring",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 2,
    "booked": 1
  },
  {
    "name": "Gabriela Maldonado Vera",
    "dept": "Unknown",
    "loc": "\u2014",
    "quoted": 2,
    "booked": 1
  },
  {
    "name": "Abhay Chaturvedi",
    "dept": "Unknown",
    "loc": "\u2014",
    "quoted": 1,
    "booked": 1
  },
  {
    "name": "Bryan Humberto Penaloza",
    "dept": "Unknown",
    "loc": "\u2014",
    "quoted": 1,
    "booked": 1
  },
  {
    "name": "Farukh Khan",
    "dept": "Unknown",
    "loc": "\u2014",
    "quoted": 1,
    "booked": 1
  },
  {
    "name": "Kalid Mora",
    "dept": "Unknown",
    "loc": "\u2014",
    "quoted": 1,
    "booked": 1
  },
  {
    "name": "Manny Alvarado",
    "dept": "Unknown",
    "loc": "\u2014",
    "quoted": 1,
    "booked": 1
  },
  {
    "name": "Jessa Rey Belontindos",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 14,
    "booked": 0
  },
  {
    "name": "Marijoh Mae Lee",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 5,
    "booked": 0
  },
  {
    "name": "Syralee Mae Gamil",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 4,
    "booked": 0
  },
  {
    "name": "Aldwin Navarro",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 3,
    "booked": 0
  },
  {
    "name": "Bueno Annalee",
    "dept": "Unknown",
    "loc": "\u2014",
    "quoted": 3,
    "booked": 0
  },
  {
    "name": "Dale Besida",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 3,
    "booked": 0
  },
  {
    "name": "Francisco Munoz",
    "dept": "Unknown",
    "loc": "\u2014",
    "quoted": 3,
    "booked": 0
  },
  {
    "name": "Kimberly Hewitt",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 3,
    "booked": 0
  },
  {
    "name": "Amisha  Kapoor",
    "dept": "Unknown",
    "loc": "\u2014",
    "quoted": 2,
    "booked": 0
  },
  {
    "name": "Dawn Carreiro",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 2,
    "booked": 0
  },
  {
    "name": "Fern Vallido",
    "dept": "Service",
    "loc": "\u2014",
    "quoted": 2,
    "booked": 0
  },
  {
    "name": "Matthew Floming",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 2,
    "booked": 0
  },
  {
    "name": "May Anthonette Clavel",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 2,
    "booked": 0
  },
  {
    "name": "Miriam Arrona",
    "dept": "Unknown",
    "loc": "\u2014",
    "quoted": 2,
    "booked": 0
  },
  {
    "name": "Nicolas Almanza",
    "dept": "Unknown",
    "loc": "\u2014",
    "quoted": 2,
    "booked": 0
  },
  {
    "name": "Ria Francisco",
    "dept": "Unknown",
    "loc": "\u2014",
    "quoted": 2,
    "booked": 0
  },
  {
    "name": "Shannon Glendye",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 2,
    "booked": 0
  },
  {
    "name": "Vanessa Flores",
    "dept": "Unknown",
    "loc": "\u2014",
    "quoted": 2,
    "booked": 0
  },
  {
    "name": "Edison Viray",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 1,
    "booked": 0
  },
  {
    "name": "Edna Espinosa",
    "dept": "Unknown",
    "loc": "\u2014",
    "quoted": 1,
    "booked": 0
  },
  {
    "name": "Katia (Katt) Herrera",
    "dept": "Unknown",
    "loc": "\u2014",
    "quoted": 1,
    "booked": 0
  },
  {
    "name": "Mariana Miranda",
    "dept": "Unknown",
    "loc": "\u2014",
    "quoted": 1,
    "booked": 0
  },
  {
    "name": "Pedro Alcala",
    "dept": "Unknown",
    "loc": "\u2014",
    "quoted": 1,
    "booked": 0
  },
  {
    "name": "Sendy Firmalino",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 1,
    "booked": 0
  },
  {
    "name": "Shella Marie Francisco",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 1,
    "booked": 0
  },
  {
    "name": "Viviane Peux",
    "dept": "SST",
    "loc": "CLW",
    "quoted": 1,
    "booked": 0
  },
  {
    "name": "Aiko Noquillo",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Anna Kathrisse Serrano",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Annalee Bueno",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Brian Valdez",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Carol Brown",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Christian Jerick Sanchez",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Christopher Monaldi",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Christopher Washington",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Cristal Apple Barredo",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Debra Springfield",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Dexter Weaver",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Erwin Cablao",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Eumarbel Dionglay",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Ferdinand Carlo Canete",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Frederick Hutchinson",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Gimarie Barastas",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Hannay Lozano",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Irish Verona",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Ivan Marc Lanestosa",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Ivy Fichtl",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "James Rebualos",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Jan Malvin Molina",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Jerico Galve",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Jerome Roger Rosites",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Jesse Vergara Jr",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Justin Brown",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Lienard Bryan Organo",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Marielle Coleen Placido",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Mary France Rodriguez",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Matthew Hepburn",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Michael Petersen",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Milkos Malcolm Orven Miguel",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Rene Dunn",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Richard Stoffregen",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Robert Dusenberry",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Ryan Dale Aldave",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Sandra Haun",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Thaddaeus Paulo Malig",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  }
],
};
