// Integrated Labor Dashboard Data — auto-generated by update_il_dashboard.py
// Report week ending: 2026-07-26

const IL_DATA = {
  updated_date: "July 26, 2026",

  // Program totals (cumulative since launch May 1, 2026)
  total_quotes:  1048,
  total_orders:  309,
  conv_rate:     29.5,

  // Cancel rate impact
  cancel_delta_7d:  -8.2,
  cancel_delta_30d: -9.5,
  cancel_delta_primary_period: 30,   // whichever window (7 or 30) has the larger-magnitude delta — drives savings
  cancel_savings:   54834,
  annualized_savings:        232904,
  projected_rollout_savings: "~$1,940,869",
  projected_rollout_agents:  400,

  labor_attach_rate: 1.7,   // manual — update when Snowflake container denominator available

  // Adoption
  active_agents: 48,
  total_agents:  130,

  // Prior week values (for trajectory narrative)
  prev_orders:  309,
  prev_quotes:  1048,
  prev_savings: 52722,

  // Department breakdown
  depts: {
    Sales: { total: 66, active: 12, orders: 137, quotes: 355, pitch_rate: 2.2, conv_rate: 38.6 },
    SST:   { total: 18,   active: 16,   orders: 122,   quotes: 394,   pitch_rate: 12.9,   conv_rate: 31.0   },
    OB:    { total: 43,    active: 17,    orders: 34,    quotes: 201,    pitch_rate: 3.1,    conv_rate: 16.9    },
  },

  // Silent agent breakdown by location + dept
  silent_grid: [
  {
    "loc": "CLW",
    "dept": "Sales",
    "total": 64,
    "silent": 54
  },
  {
    "loc": "CLW",
    "dept": "SST",
    "total": 5,
    "silent": 0
  },
  {
    "loc": "CLW",
    "dept": "OB",
    "total": 13,
    "silent": 6
  },
  {
    "loc": "CNX",
    "dept": "Sales",
    "total": 2,
    "silent": 0
  },
  {
    "loc": "CNX",
    "dept": "SST",
    "total": 13,
    "silent": 2
  },
  {
    "loc": "CNX",
    "dept": "OB",
    "total": 30,
    "silent": 20
  }
],

  // Weekly new quotes & orders (last 8 weeks) — for stacked bar chart
  weekly_trends: [
  {
    "week": "6/1-6/7",
    "quotes": 95,
    "orders": 30
  },
  {
    "week": "6/8-6/14",
    "quotes": 104,
    "orders": 25
  },
  {
    "week": "6/15-6/21",
    "quotes": 95,
    "orders": 22
  },
  {
    "week": "6/22-6/28",
    "quotes": 85,
    "orders": 24
  },
  {
    "week": "6/29-7/5",
    "quotes": 77,
    "orders": 18
  },
  {
    "week": "7/6-7/12",
    "quotes": 93,
    "orders": 34
  },
  {
    "week": "7/13-7/19",
    "quotes": 99,
    "orders": 31
  },
  {
    "week": "7/20-7/26",
    "quotes": 120,
    "orders": 42
  }
],

  // This week vs last week, by department
  dept_wow: {
  "Sales": {
    "quotes_cur": 48,
    "quotes_prev": 29,
    "orders_cur": 23,
    "orders_prev": 14
  },
  "SST": {
    "quotes_cur": 31,
    "quotes_prev": 41,
    "orders_cur": 13,
    "orders_prev": 13
  },
  "OB": {
    "quotes_cur": 28,
    "quotes_prev": 12,
    "orders_cur": 4,
    "orders_prev": 2
  }
},

  // This week vs last week, by agent (only agents with activity in either week)
  agent_wow: [
  {
    "name": "Almira Castro",
    "dept": "SST",
    "loc": "CNX",
    "quotes_cur": 0,
    "quotes_prev": 2,
    "orders_cur": 0,
    "orders_prev": 0
  },
  {
    "name": "Amy Sisterman",
    "dept": "Sales",
    "loc": "CLW",
    "quotes_cur": 14,
    "quotes_prev": 10,
    "orders_cur": 4,
    "orders_prev": 3
  },
  {
    "name": "Anna Kathrisse Serrano",
    "dept": "SST",
    "loc": "CNX",
    "quotes_cur": 2,
    "quotes_prev": 0,
    "orders_cur": 0,
    "orders_prev": 0
  },
  {
    "name": "Carmie Ann Gorospe",
    "dept": "SST",
    "loc": "CNX",
    "quotes_cur": 2,
    "quotes_prev": 0,
    "orders_cur": 2,
    "orders_prev": 0
  },
  {
    "name": "Carmie Nillama",
    "dept": "SST",
    "loc": "CNX",
    "quotes_cur": 2,
    "quotes_prev": 3,
    "orders_cur": 0,
    "orders_prev": 2
  },
  {
    "name": "Catherine Saitta",
    "dept": "Sales",
    "loc": "CLW",
    "quotes_cur": 6,
    "quotes_prev": 9,
    "orders_cur": 5,
    "orders_prev": 9
  },
  {
    "name": "Charmaine Bacay",
    "dept": "OB",
    "loc": "CNX",
    "quotes_cur": 13,
    "quotes_prev": 2,
    "orders_cur": 1,
    "orders_prev": 0
  },
  {
    "name": "Christina Morales",
    "dept": "OB",
    "loc": "CLW",
    "quotes_cur": 6,
    "quotes_prev": 0,
    "orders_cur": 2,
    "orders_prev": 0
  },
  {
    "name": "Christopher Monaldi",
    "dept": "OB",
    "loc": "CLW",
    "quotes_cur": 2,
    "quotes_prev": 0,
    "orders_cur": 0,
    "orders_prev": 0
  },
  {
    "name": "Dale Besida",
    "dept": "OB",
    "loc": "CLW",
    "quotes_cur": 0,
    "quotes_prev": 1,
    "orders_cur": 0,
    "orders_prev": 0
  },
  {
    "name": "Dawn Carreiro",
    "dept": "OB",
    "loc": "CLW",
    "quotes_cur": 2,
    "quotes_prev": 0,
    "orders_cur": 1,
    "orders_prev": 0
  },
  {
    "name": "Donald Alfaro",
    "dept": "SST",
    "loc": "CLW",
    "quotes_cur": 2,
    "quotes_prev": 3,
    "orders_cur": 0,
    "orders_prev": 1
  },
  {
    "name": "Ednalyn Mirandilla",
    "dept": "OB",
    "loc": "CNX",
    "quotes_cur": 1,
    "quotes_prev": 0,
    "orders_cur": 0,
    "orders_prev": 0
  },
  {
    "name": "Felicia Knight",
    "dept": "SST",
    "loc": "CLW",
    "quotes_cur": 1,
    "quotes_prev": 2,
    "orders_cur": 1,
    "orders_prev": 0
  },
  {
    "name": "Gregory D. Bell",
    "dept": "Sales",
    "loc": "CLW",
    "quotes_cur": 8,
    "quotes_prev": 3,
    "orders_cur": 4,
    "orders_prev": 0
  },
  {
    "name": "Jake Russel Bernardino",
    "dept": "OB",
    "loc": "CNX",
    "quotes_cur": 1,
    "quotes_prev": 2,
    "orders_cur": 0,
    "orders_prev": 1
  },
  {
    "name": "James Onnagan",
    "dept": "SST",
    "loc": "CNX",
    "quotes_cur": 2,
    "quotes_prev": 5,
    "orders_cur": 2,
    "orders_prev": 4
  },
  {
    "name": "Jeanielle Navarro",
    "dept": "SST",
    "loc": "CNX",
    "quotes_cur": 4,
    "quotes_prev": 5,
    "orders_cur": 0,
    "orders_prev": 1
  },
  {
    "name": "Jessa Rey Belontindos",
    "dept": "OB",
    "loc": "CNX",
    "quotes_cur": 3,
    "quotes_prev": 5,
    "orders_cur": 0,
    "orders_prev": 1
  },
  {
    "name": "Johnny Cardinale",
    "dept": "SST",
    "loc": "CLW",
    "quotes_cur": 6,
    "quotes_prev": 10,
    "orders_cur": 2,
    "orders_prev": 1
  },
  {
    "name": "Katleen May Castro",
    "dept": "Sales",
    "loc": "CNX",
    "quotes_cur": 6,
    "quotes_prev": 5,
    "orders_cur": 1,
    "orders_prev": 0
  },
  {
    "name": "Kimberly Hewitt",
    "dept": "OB",
    "loc": "CLW",
    "quotes_cur": 0,
    "quotes_prev": 1,
    "orders_cur": 0,
    "orders_prev": 0
  },
  {
    "name": "Kimberly Thebeau",
    "dept": "Sales",
    "loc": "CLW",
    "quotes_cur": 3,
    "quotes_prev": 0,
    "orders_cur": 2,
    "orders_prev": 0
  },
  {
    "name": "Maria Concepcion Cauguiran",
    "dept": "SST",
    "loc": "CNX",
    "quotes_cur": 1,
    "quotes_prev": 2,
    "orders_cur": 0,
    "orders_prev": 0
  },
  {
    "name": "May Anthonette Clavel",
    "dept": "OB",
    "loc": "CNX",
    "quotes_cur": 0,
    "quotes_prev": 1,
    "orders_cur": 0,
    "orders_prev": 0
  },
  {
    "name": "Mica Mae Maniego",
    "dept": "SST",
    "loc": "CNX",
    "quotes_cur": 4,
    "quotes_prev": 0,
    "orders_cur": 3,
    "orders_prev": 0
  },
  {
    "name": "Micah Joy Abrao",
    "dept": "SST",
    "loc": "CNX",
    "quotes_cur": 1,
    "quotes_prev": 2,
    "orders_cur": 0,
    "orders_prev": 0
  },
  {
    "name": "Nicole Slater",
    "dept": "Sales",
    "loc": "CLW",
    "quotes_cur": 3,
    "quotes_prev": 0,
    "orders_cur": 1,
    "orders_prev": 1
  },
  {
    "name": "Princess Heidi Sesma",
    "dept": "Service",
    "loc": "CNX",
    "quotes_cur": 3,
    "quotes_prev": 0,
    "orders_cur": 0,
    "orders_prev": 0
  },
  {
    "name": "Sara Messenger",
    "dept": "SST",
    "loc": "CLW",
    "quotes_cur": 4,
    "quotes_prev": 7,
    "orders_cur": 3,
    "orders_prev": 4
  },
  {
    "name": "Shannon Glendye",
    "dept": "Sales",
    "loc": "CLW",
    "quotes_cur": 0,
    "quotes_prev": 1,
    "orders_cur": 0,
    "orders_prev": 0
  },
  {
    "name": "Michael Alcalde",
    "dept": "Sales",
    "loc": "CLW",
    "quotes_cur": 3,
    "quotes_prev": 0,
    "orders_cur": 2,
    "orders_prev": 0
  },
  {
    "name": "Kasey M. Lockhart",
    "dept": "Sales",
    "loc": "CLW",
    "quotes_cur": 5,
    "quotes_prev": 1,
    "orders_cur": 4,
    "orders_prev": 1
  },
  {
    "name": "HaH Agent",
    "dept": "HaH",
    "loc": "\u2014",
    "quotes_cur": 10,
    "quotes_prev": 17,
    "orders_cur": 2,
    "orders_prev": 2
  }
],

  // Opportunity table
  opp_table: [
  {
    "dept": "OB",
    "desc": "All 43 fully trained",
    "silent": 26,
    "est_containers": "~3,320",
    "est_missed": "~442",
    "priority": "Critical"
  },
  {
    "dept": "Sales",
    "desc": "54 silent",
    "silent": 54,
    "est_containers": "~1,401",
    "est_missed": "~187",
    "priority": "High"
  },
  {
    "dept": "SST",
    "desc": "2 silent",
    "silent": 2,
    "est_containers": "~361",
    "est_missed": "~48",
    "priority": "Moderate"
  }
],

  // Agent roster (cumulative since launch)
  agents: [
  {
    "name": "Catherine Saitta",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 56,
    "booked": 44
  },
  {
    "name": "Amy Sisterman",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 96,
    "booked": 33
  },
  {
    "name": "Jeanielle Navarro",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 75,
    "booked": 24
  },
  {
    "name": "Sara Messenger",
    "dept": "SST",
    "loc": "CLW",
    "quoted": 49,
    "booked": 20
  },
  {
    "name": "Johnny Cardinale",
    "dept": "SST",
    "loc": "CLW",
    "quoted": 57,
    "booked": 18
  },
  {
    "name": "Gregory D. Bell",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 61,
    "booked": 14
  },
  {
    "name": "Carmie Nillama",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 50,
    "booked": 14
  },
  {
    "name": "Kimberly Thebeau",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 45,
    "booked": 13
  },
  {
    "name": "Ted Johnson",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 29,
    "booked": 11
  },
  {
    "name": "James Onnagan",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 18,
    "booked": 11
  },
  {
    "name": "HaH Agent",
    "dept": "HaH",
    "loc": "\u2014",
    "quoted": 80,
    "booked": 10
  },
  {
    "name": "Felicia Knight",
    "dept": "SST",
    "loc": "CLW",
    "quoted": 28,
    "booked": 10
  },
  {
    "name": "Christina Morales",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 25,
    "booked": 10
  },
  {
    "name": "Charmaine Bacay",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 69,
    "booked": 9
  },
  {
    "name": "Mica Mae Maniego",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 22,
    "booked": 7
  },
  {
    "name": "Nicole Slater",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 19,
    "booked": 6
  },
  {
    "name": "Princess Heidi Sesma",
    "dept": "Service",
    "loc": "CNX",
    "quoted": 16,
    "booked": 6
  },
  {
    "name": "Kasey M. Lockhart",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 7,
    "booked": 6
  },
  {
    "name": "Donald Alfaro",
    "dept": "SST",
    "loc": "CLW",
    "quoted": 22,
    "booked": 5
  },
  {
    "name": "Micah Joy Abrao",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 12,
    "booked": 5
  },
  {
    "name": "Michael Alcalde",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 7,
    "booked": 5
  },
  {
    "name": "Katleen May Castro",
    "dept": "Sales",
    "loc": "CNX",
    "quoted": 27,
    "booked": 4
  },
  {
    "name": "Christopher Monaldi",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 18,
    "booked": 4
  },
  {
    "name": "Jake Russel Bernardino",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 13,
    "booked": 4
  },
  {
    "name": "Almira Castro",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 14,
    "booked": 3
  },
  {
    "name": "Carmie Ann Gorospe",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 9,
    "booked": 3
  },
  {
    "name": "Jessa Rey Belontindos",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 39,
    "booked": 2
  },
  {
    "name": "Maria Concepcion Cauguiran",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 24,
    "booked": 2
  },
  {
    "name": "Ednalyn Mirandilla",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 7,
    "booked": 2
  },
  {
    "name": "Dawn Carreiro",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 4,
    "booked": 1
  },
  {
    "name": "Aldwin Navarro",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 3,
    "booked": 1
  },
  {
    "name": "Erik Goldring",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 2,
    "booked": 1
  },
  {
    "name": "Ria Francisco",
    "dept": "Sales",
    "loc": "CNX",
    "quoted": 2,
    "booked": 1
  },
  {
    "name": "Marijoh Mae Lee",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 5,
    "booked": 0
  },
  {
    "name": "Shannon Glendye",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 5,
    "booked": 0
  },
  {
    "name": "Viviane Peux",
    "dept": "SST",
    "loc": "CLW",
    "quoted": 5,
    "booked": 0
  },
  {
    "name": "Dale Besida",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 4,
    "booked": 0
  },
  {
    "name": "Kimberly Hewitt",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 4,
    "booked": 0
  },
  {
    "name": "Syralee Mae Gamil",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 4,
    "booked": 0
  },
  {
    "name": "Annalee Bueno",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 3,
    "booked": 0
  },
  {
    "name": "May Anthonette Clavel",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 3,
    "booked": 0
  },
  {
    "name": "Anna Kathrisse Serrano",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 2,
    "booked": 0
  },
  {
    "name": "Fern Vallido",
    "dept": "Service",
    "loc": "\u2014",
    "quoted": 2,
    "booked": 0
  },
  {
    "name": "Matthew Floming",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 2,
    "booked": 0
  },
  {
    "name": "Donavan O. Mitchell",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 1,
    "booked": 0
  },
  {
    "name": "Edison Viray",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 1,
    "booked": 0
  },
  {
    "name": "Sendy Firmalino",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 1,
    "booked": 0
  },
  {
    "name": "Shella Marie Francisco",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 1,
    "booked": 0
  },
  {
    "name": "Aiko Noquillo",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Alexander Cook",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Alfred Thornton",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Alton Nelson",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Amy Ashmore",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Arlene Wethern",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Ashley Burrell",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Blake Waters",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Brian C. Quinn",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Brian Valdez",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Carol Brown",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Caroline McMahon",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Charles Chambliss",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Cheryl Rosa",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Christian Jerick Sanchez",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Christopher Carlesimo",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Christopher Washington",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Cristal Apple Barredo",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Debra Springfield",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Dexter Weaver",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Erwin Cablao",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Eumarbel Dionglay",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Ferdinand Carlo Canete",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Frank Miedzianowski",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Frederick Hutchinson",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Gavin Novak",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Gennaro Guardascione",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Gentian Grezda",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Gimarie Barastas",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Hannay Lozano",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Heidi Gathen",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Henry Noble",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Henssy Henriquez",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Irish Verona",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Ivan Marc Lanestosa",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Ivy Fichtl",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Jalmise Victor",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "James Jackson",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "James Meckfessel",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "James P. Dempsey Jr.",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "James Rebualos",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Jan Malvin Molina",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Jerico Galve",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Jerome Roger Rosites",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Jesse Vergara Jr",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Jordan Rosario Garcia",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Jorden N. Murray",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Joy Hall",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Justin Brown",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Justin Myers Singh",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Kelvin Pearce",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "LaQuishia Brown",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "LaVerne Reed",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Latoya Jones",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Leanne Souza",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Lienard Bryan Organo",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Lynna Stites",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Madeline Quiros",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Marielle Coleen Placido",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Mary France Rodriguez",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Matthew Hepburn",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Michael Petersen",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Milkos Malcolm Orven Miguel",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Nathaniel Herden",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Patricia Paino",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Rene Dunn",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Richard Stoffregen",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Robert Dusenberry",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Ryan Dale Aldave",
    "dept": "SST",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Sakeema McCray",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Sandra Haun",
    "dept": "OB",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Scot Horowitz",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Scott Scalzo",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Scott Schneider",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Seiha Ly",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Shayla Brown",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Stephen Hardwick",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Tanisha Lee",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Thaddaeus Paulo Malig",
    "dept": "OB",
    "loc": "CNX",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Tracy Heath",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Valerie Mabe",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  },
  {
    "name": "Wendy Horowitz",
    "dept": "Sales",
    "loc": "CLW",
    "quoted": 0,
    "booked": 0
  }
],
};
